### ISSUE TITLE
about NN : 12 aspects

### ISSUE THREAD

**Issue by tissatussa** [alcides-schulz/Tucano#10]
[ if this is all true, my 12 could be 13 .. or the amount can be deduced ]

I see many chess engine programmers develop their own NN.
I have questions.

Chess is my passion and i use chess engines to learn and see (new) patterns.
For that, i found and compose several positions which need some insight to play good moves.

Chess could be one big puzzle.
I suspect each position is a combination of (12) aspects, like

> material
> space
> time
> tempo
> initiative
> king safety
> ..

I find some chess engines have multi options concerning such parameters,
but no benchmark / tests exist !?
same for NNs : can self play ever give new patterns ?
how to test the result of NN trainings ?  

to contemplate i give 3 positions.
they have their own special 'aspects'.

---

diagram below : White to move.
here White is 2 pieces ahead but poorly developed and the King is in danger.
many constellations and complications can arise.
it's hard to make a draw or even win.
this is from an existing opening variation, i forgot which ..
i think it's a good idea to train your NN with unbalanced positions with many 'aspects'.

r4rk1/pQpp1ppp/1b3q2/4p3/8/2P2N2/PP2KnPP/RNB2BR1 w - - 0 1

![tucano_diagram2](https://user-images.githubusercontent.com/1109281/151717314-e7f42e28-549e-4a2b-8078-91e028e8dd62.png)

---

diagram below : White to move.
here White can (!spoiler!) do f6! and win on the White squares.
most engines (in fact none) do not find this key move, the 'solution' of this 'puzzle' is beyond their variation tree horizon .. why don't engines calculate / evaluate the white and black square complexes separately ?  Then it's easy to find f6! ?
also see my Issue https://github.com/algerbrex/blunder/issues/13

rk6/pP1p2p1/B7/3K1P2/8/8/7b/8 w - - 0 1

![chess - just win on the white squares](https://user-images.githubusercontent.com/1109281/151717311-643ca33b-8685-4464-87c4-9657ab87e43f.png)

---

diagram below : White to move.
it's an endgame from a fixed starting position, which was composed to induce all kinds of complications, while 'zugzwang' occurs because each player has only two knights and some pawns.
Black has a plus pawn and should be able to win this position, but White can draw in many ways.
many constellations and complications can arise.
a few basic chess principles are involved in this position : it shows how tempo, material and the threat of promotion intertwine.
also see my Issue https://github.com/bagaturchess/Bagatur/issues/16

8/p5pp/1pk5/5p2/P1nn4/2NN3P/5PPK/8 w - - 0 1

![4Npos](https://user-images.githubusercontent.com/1109281/151717302-a4ab02d0-2424-4837-bba9-e8818956e5f4.png)

---

what are your thoughts ?
can we ever train a NN for "such positions" ?
can a programmer be able to derive certain aspects in each position,
and determine a suitable "eval approach" / eg. NN type ?

are you a chess player too ?
i'm a club player with rating about 1850
(but i can beat 2000+ while they're playing moves i expect).

**what is a chess style ?**
https://www.bitchute.com/video/B4AJBsTusLAh/

**Comment by alcides-schulz** [comment]
Hi, I'm new to NN technology but from my understanding the NN learns those aspects of the position with the training. When doing hand-crafted evals, you have to pretty code most of those aspects.
I particularly like the NN approach, since I can focus more on the search, and I'm not that in chess :)
Thanks.
