### ISSUE TITLE
Tucano 10 for Mac M1

### ISSUE THREAD

**Issue by microsmeta** [alcides-schulz/Tucano#12]
Hi!
I'm trying to compile Tucano, but I get this error:

(I've removed -march=native from makefile because is incompatible)

Could you help me (or build youself also for Mac M1) ?

Best regards, Alex

cd Tucano-220908/src
alessandromorales@MinidiAessandro src % make ARCH=apple-silicon
gcc -O3 -DEGTB_SYZYGY -Wall -Wextra -flto  *.c fathom/tbprobe.c -o tucano_old -lpthread -lm
ld: <inline asm>:1:2: unrecognized instruction mnemonic
        bsfq [x12], x15
        ^
 for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [old] Error 1
alessandromorales@MinidiAessandro src % 

In the meanwhile, 10.08 compiled fine for Windows sse41 popcnt :-) 
Let me know if you want that I compile the source for M1  for you with your modified makefile

Tucano chess engine by Alcides Schulz - 10.08 (type 'help' for information)
   hash table: 64 MB, threads: 1

bench
Benchmark (depth=16)
1/16) 3r2k1/pp2b1pp/5p2/4p3/3r4/P2P2BP/1P3PP1/1R1R1K2 b -- - 0 24
2/16) rn1qk1nr/pp3pp1/2pbp1p1/8/2pP1BP1/2N5/PP1QPPBP/R3K2R b KQkq - 0 10
3/16) r1bq1rk1/ppppbppp/2n5/1B6/4P3/3Q4/PPP2PPP/RNB2RK1 w -- - 0 9
4/16) 8/2B4k/R6p/1p3pp1/1P6/2P1r1K1/2n5/8 w -- - 0 46
5/16) r1b1kbnr/6pp/p1pq1p2/3p4/4P3/5N2/PPP2PPP/RNBQR1K1 w -kq - 0 10
6/16) N1bk4/bp1p4/p1nN1p1p/4p3/1PB1P1pq/2PP4/P4PP1/R2Q1RK1 w -- - 0 19
7/16) 1r2r1k1/3bnppp/p2q4/2RPp3/4P3/6P1/2Q1NPBP/2R3K1 w - -
8/16) 1qr3k1/p2nbppp/bp2p3/3p4/3P4/1P2PNP1/P2Q1PBP/1N2R1K1 b - -
9/16) 2b1k2r/2p2ppp/1qp4n/7B/1p2P3/5Q2/PPPr2PP/R2N1R1K b k -
10/16) 2b5/1p4k1/p2R2P1/4Np2/1P3Pp1/1r6/5K2/8 w - -
11/16) 2brr1k1/ppq2ppp/2pb1n2/8/3NP3/2P2P2/P1Q2BPP/1R1R1BK1 w - -
12/16) 2kr2nr/1pp3pp/p1pb4/4p2b/4P1P1/5N1P/PPPN1P2/R1B1R1K1 b - -
13/16) 2r1k2r/1p1qbppp/p3pn2/3pBb2/3P4/1QN1P3/PP2BPPP/2R2RK1 b k -
14/16) 2r1r1k1/pbpp1npp/1p1b3q/3P4/4RN1P/1P4P1/PB1Q1PB1/2R3K1 w - -
15/16) 2r2k2/r4p2/2b1p1p1/1p1p2Pp/3R1P1P/P1P5/1PB5/2K1R3 w - -
16/16) 2r3k1/5pp1/1p2p1np/p1q5/P1P4P/1P1Q1NP1/5PK1/R7 w - -

Signature: 5203395  Elapsed time: 49.59 secs  Nodes/sec:  105k 

It Is much faster ( bench was running in multitasking) 1.6 Mn/s with 4 CPUs

**Comment by alcides-schulz** [comment]
Hi I'm sorry for this late reply, somehow I missed this item here. I don't know if this still relevant. 
I don't have experience with MAC compiles. I'm not sure if how can i help.
If you still wants to take a look, let me know I can also look and research a solution. 
Let me know and again, apologies for the late response.

**Comment by alcides-schulz** [comment]
Closing issue, can be reopen if needed.
