### ISSUE TITLE
Linux compile OK but does not play correctly

### ISSUE THREAD

**Issue by tissatussa** [alcides-schulz/Tucano#8]
Tucano v9.07 compiles OK on Xubuntu 20.04, but playing fails when testing in CuteChess : a first move is played, but then the "connection stalls".  The CuteChess log window shows that Tucano considered a (correct) second move, but it isn't played ..

**Comment by tissatussa** [comment]
i compiled your Tucano v9(.18) and i tried to play in CuteChess but it failed .. I use Xubuntu 20.04 .. at first Tucano normally starts the game and played 1 move with White, but after Blacks reply Tucano thinks forever and gives no output and its "connection stalls" after exceeding the time limit ..!?

here are the CuteChess 'debug logs' of the ending of 2 games :


```

<Clover v2.4(47): info depth 22 currmove h7h5 currmovenumber 34
<Clover v2.4(47): info depth 22 currmove c6b8 currmovenumber 35
<Clover v2.4(47): info score cp -178 depth 22 seldepth 44 nodes 17872883 nps 1318934 time 13551 tbhits 0 hashfull 972 pv d8e7 f7h8 f2c5 d2d3 d7d6 c4f7 e8d8 h2h3 e7f8 f1e1 f8h8 h1f1 h8f8 f7b3 h7h6 b1c3 f8e7 c3a4 c5b4 c1d2 b4d2 e1d2 c8d7 a4c3 c6d4 c3e2 d4b3 a2b3 d6d5 e2c3 d5e4 d3e4 
<Clover v2.4(47): info depth 24 currmove d8e7 currmovenumber 1
<Tucano v9.18(46): info depth 25 score cp 255 time 15539 nodes 21866756 nps 1407217 tbhits 0 pv f7h8 f2c5 d2d3 d7d6 b1d2 c8e6 c4e6 e7e6 d2f3 e6g8 c2c3 g8h8 b2b4 c5b6 a2a4 a7a5 b4b5 c6e7 d1b3 h8f8 b3e6 f6d7 c1g5 d7c5 e6e7 f8e7 g5e7 e8e7 f1e2 a8f8
<Clover v2.4(47): bestmove d8e7
>Tucano v9.18(46): ponderhit
>Tucano v9.18(46): stop
>Clover v2.4(47): isready
<Clover v2.4(47): readyok



<SF v14 OF no NN(49): info depth 36 currmove g7g5 currmovenumber 38
<SF v14 OF no NN(49): info depth 36 currmove g7g6 currmovenumber 39
<SF v14 OF no NN(49): info depth 36 seldepth 47 multipv 1 score cp -228 nodes 265270645 nps 1457242 hashfull 999 tbhits 0 time 182036 pv f2b6 c4f7 e8d8 b1c3 d7d6 h2h3 e7f8 g2g3 f8h8 f1g2 c8d7 d2d3 c6e7 d1f3 h7h6 c1e3 b6e3 f3e3 a7a5 a1f1 d8c8 e3f3 b7b6 c3d5 e7d5 f7d5 c7c6 d5f7 c8b7 a2a4 h8h7 f7c4 a8f8 f3e3 h6h5 e3g5
<SF v14 OF no NN(49): info depth 37 currmove f2b6 currmovenumber 1
>SF v14 OF no NN(49): stop
<SF v14 OF no NN(49): info depth 37 seldepth 47 multipv 1 score cp -228 nodes 277708660 nps 1456190 hashfull 999 tbhits 0 time 190709 pv f2b6 c4f7 e8d8 b1c3 d7d6 h2h3 e7f8 g2g3 f8h8 f1g2 c8d7 d2d3 c6e7 d1f3 h7h6 c1e3 b6e3 f3e3 a7a5 a1f1 d8c8 e3f3 b7b6 c3d5 e7d5 f7d5 c7c6 d5f7 c8b7 a2a4 h8h7 f7c4 a8f8 f3e3 h6h5 e3g5
<SF v14 OF no NN(49): bestmove f2b6 ponder c4f7
>SF v14 OF no NN(49): isready
<SF v14 OF no NN(49): readyok
```

**Comment by tissatussa** [comment]
does anyone have the same error ?  Can you solve this ?

![tucano_error](https://user-images.githubusercontent.com/1109281/141687358-c2f1dd8d-c3f3-4956-b035-875e39153d80.png)

**Comment by alcides-schulz** [comment]
Hi, sorry you having this issue. 
We have a new tucano release, version 10. But not sure if it can solve, since didn't have  a time control change in this version.
I also have cutechess, I can run in linux (centos). Can you provide the information from the cutechess time control. I can do some research to try to locate the problem.
Thanks.

**Comment by tissatussa** [comment]
i just compiled the newest v10.01 by "git clone" and it seems to work when executing in terminal, but in CuteChess it fails :

![Tucano_v10 01_error_in_cutechess](https://user-images.githubusercontent.com/1109281/150778508-23424590-db2e-466d-9efc-4366876fc9b4.png)

my compilation is done on another laptop (only having SSE4, not AVX2 as my previous notebook) but i had no errors while compiling .. i also have the NN and it's loaded .. it seems Tucano doesn't know the command "go movetime", like some other (simple) engines .. is this true ?  Then that must be the cause.
Btw. i'm using Linux Devuan Chimaera 4.0, a Debian derivative.
Here is the ZIPped CuteChess "debug log" of this short game :
[tucano_10.01_cutechess_debug_log.zip](https://github.com/alcides-schulz/Tucano/files/7925509/tucano_10.01_cutechess_debug_log.zip)

**Comment by alcides-schulz** [comment]
Hi thanks for providing the log, I have to do some research. I can see in the log that you are using ponder ON. I tested this with arena gui, I have to do some tests with cutechess. Let you know when I find something.
For now, if this helps, maybe you can try running with ponder OFF. 
I think "go movetime" should be ok, but maybe with the combination with ponder may be causing the issue. I'll take a look.
thanks

**Comment by tissatussa** [comment]
indeed : ponder OFF is needed !
i could have thought of that, but i didn't .. so, thanks!

**Comment by alcides-schulz** [comment]
You're welcome. I will keep this issue open, I will take a look, since that should work. Let you know. Thanks.

**Comment by alcides-schulz** [comment]
Hi, I just pushed a fix to this issue. It was actually a bug when using ponder option. If you want you can download the latest version 10.02 and take a look. Thanks for reporting that. I will close this, but in case of any issue please let me know.
thanks.

**Comment by tissatussa** [comment]
i searched your GitHub pages but i can't find that 10.02 version .. can you give a link? I can also compile some source, but only Linux (no Centos).

ohhh .. now i see your comment at the src folder : "Fix issue with ponder related to multi-thread in uci" .. so i will compile that.

**Comment by alcides-schulz** [comment]
Hi,
It is the current version in github. you can download the latest source code version but have to compile.
For now i will make changes, but will take some time for a new official release.
thanks.
Let me know.

Alcides.

https://github.com/alcides-schulz/Tucano


[https://opengraph.githubassets.com/be961368f99c6bba99743ca9af1449ec50108db64c4f50566dbfa1c6df1340c3/alcides-schulz/Tucano]<https://github.com/alcides-schulz/Tucano>
GitHub - alcides-schulz/Tucano: Tucano Chess Engine<https://github.com/alcides-schulz/Tucano>
Tucano. Tucano Chess Engine . This is my chess engine Tucano (Toucan in english). It is the name of a colorful bird with an oversized bill, and is popular in my country Brazil.
github.com


________________________________

**Comment by tissatussa** [comment]
I successfully compiled that 10.02 source and it runs fine in CuteChess!

Tucano 10.02 even made a nice draw in the following position which i recently use to test and see engines play.
White to move. It's a very unbalanced position, White is two pieces ahead but has a very poor development and a weak King. Only a few engines can draw this, almost none of them can win with White. Andscacs 0.95 has rating 3180 and the game time was 8 min + 3 sec per player for the whole game. See PGN  
[tucano_good_play.zip](https://github.com/alcides-schulz/Tucano/files/7966328/tucano_good_play.zip) - thinking times are supplied. 

r4rk1/pQpp1ppp/1b3q2/4p3/8/2P2N2/PP2KnPP/RNB2BR1 w - - 0 1

![tucano_diagram](https://user-images.githubusercontent.com/1109281/151707597-f00cf4ce-fdb4-49c0-bedf-3e412de9cc4b.png)

**Comment by alcides-schulz** [comment]
Hi,
Glad it worked. As I said it was a bug in the ponder option. I'm happy it is fixed!

This NN stuff is really good, I always find that tucano eval was not good, but the NN replaced it, and really improved the gameplay.  I'm working on a new version of tucano nn.
The position below seems very trick indeed. Thanks for testing that.

All the best.
Alcides.


________________________________

**Comment by tissatussa** [comment]
Nice! I want to discuss some more NN with you .. i will open a new "issue" for that .. i'm only a user of engines, for fun and because i'm a passionated chess player, and i'm a programmer too, but no engine yet. Happy hacking !

See one of my edits :
**how engines play**
https://www.bitchute.com/video/lt26Q2qpeEUS/
